from . import department
from . import division
from . import student
from . import teacher
from . import classes
from . import fees
from . import admission
from . import attendance
from . import subject
from . import nutshell_letters
from . import nutshell_employee